# Generated by Django 2.2.16 on 2020-10-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyersguide', '0005_update_created_date'),
        ('wagtailpages', '0015_buyersguidepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='legacy_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyersguide.Product'),
        ),
    ]
